dist: xenial
sudo: required
language: python
cache: pip

python:
  - '3.7'
addons:
  apt:
    packages:
      - jq
      - moreutils
      - gettext
install: "pip install -r requirements-dev.txt -r requirements.txt"

jobs:
  include:
    - stage: Unit Test
      script:
        - source config/environment
        - make test
